# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js for the frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./react-frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./react-frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username : ramzworks
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./react-frontend/Dockerfile
          push: true
          tags: ramzworks/demoapp:latest
